config/routes.rb
Rails.application.routes.draw do
 

  devise_for :users
  resources :deliveries do 
     resources :reviews, except: [:show, :index]
   end
   
  get 'pages/about'

  get 'pages/contact'

  root 'deliveries#index'

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :reviews

	validates :name, :address, :phone, :name, :image, presence: true
	validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
	 message: "must be in the format (123) 456-7890" }
	 validates :address, format: { with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
	 message: "must be in the format 350 Fifth Avenue, New York, NY 10118"}
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :delivery

	validates :rating, :comment, presence: true
	validates :rating, numericality: {
		only_integer: true,
		greater_than_or_equal_to: 1,
		less_than_or_equal_to: 5,
		message: "can only be a whole number between 1 and 5"
	}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy 
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
	devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
	devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
	devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
  end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show]
  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
    @reviews = Review.where(delivery_id: @delivery.id)
    if @reviews.blank?
      @avg_rating = 0
    else
    @vg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)

    respond_to do |format|
      if @delivery.save
        format.html { redirect_to @delivery, notice: 'Delivery was successfully created.' }
        format.json { render :show, status: :created, location: @delivery }
      else
        format.html { render :new }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_params
      params.require(:delivery).permit(:name, :address, :phone, :size, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_delivery
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]
    # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.delivery_id = @delivery.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to delivery_path(@delivery), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to delivery_path(@delivery), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_delivery      
      @delivery = Delivery.find(params[:delivery_id])
    end

     def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Sorry, this review belongs to someone else."
       end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
			sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count,
				resource: resource.class.model_name.human.downcase)

			html = <<-HTML
			<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
			<span class="sr-only">Close</span>
			</button>
			<h4>#{sentence}</h4>
			#{messages}
			</div>
			HTML

			html.html_safe
		end
	end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/deliveries/_form.html.erb
<%= form_for(@delivery, :html => { multipart: true}) do |f| %>
  <% if @delivery.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
    </button>
      <h4><%= pluralize(@delivery.errors.count, "error") %> prohibited this delivery from being saved:</h4>

      <ul>
      <% @delivery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "iPhone" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "469 West Bank Ave, Minneapolis, MN 55369" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "(321) 789-9654" %>
  </div>
  <div class="form-group">
    <%= f.label :size %><br>
    <%= f.text_field :size, class: "form-control", placeholder: "Large" %>
  </div>
  <div class="form-group">
    <%= f.label :image%><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing Delivery</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery, class: "btn btn-link" %> |
<%= link_to 'Back', deliveries_path, class: "btn btn-link" %>

app/views/deliveries/index.html.erb
<div class="jumbotron">
  <h1>NextPakk Go</h1>
  <p>The Smart, Secure, Convenient way for package delivery! "We've Got Your Pack"</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

<h1>Listing Deliveries</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Size</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= link_to delivery.name, delivery %></td>
        <td><%= link_to delivery.address, "http://maps.google.com/?q=#{delivery.address}" %>          
        </td>      
        <td><%= delivery.phone %></td>
        <td><%= delivery.size %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_delivery_path(delivery), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', delivery, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Delivery', new_delivery_path %>
<% end %>

app/views/deliveries/new.html.erb
<h1>New Delivery</h1>

<%= render 'form' %>

<%= link_to 'Back', deliveries_path, class: "btn btn-link" %>

app/views/deliveries/show.html.erb
<div class="row">
	<div class="col-md-4">
		<div id="imgZ" style="width:300px; min-height:240px; padding-bottom:10px;"><%= image_tag @delivery.image_url, class: "img-responsive" %>

		</div>

		<h2>
		  <strong>Name:</strong>
		  <%= @delivery.name %>
		  <div class="star-rating" data-score= <%= @avg_rating %> >
		</h2>

		<p>
		  <strong>Address:</strong>
		  <%= link_to @delivery.address, "http://maps.google.com/?q=#{@delivery.address}" %>
		</p>	 

		<p>
		  <strong>Phone:</strong>
		  <%= @delivery.phone %>
		</p>

		<p>
		  <strong>Size:</strong>
		  <%= @delivery.size %>
		</p>

		<%= link_to "Write a Review", new_delivery_review_path(@delivery), class: "btn btn-primary" %><br /><br />

		<%= link_to 'Edit', edit_delivery_path(@delivery) %> |
		<%= link_to 'Back', deliveries_path %>
	</div>

	<div class="col-md-8">
	<% if @reviews.blank? %>
		<h2>No reviews yet. Be the first to write one!</h2>
	<% else %>
	<table>
		<thead>
			<tr>
				<th class="col-md-4"></th>
				<th class="col-md-8"></th>
			</tr>
		</thead>
		<tbody>
			<% @reviews.each do |review| %>
			<tr>
				<td>
					<h4>
						<%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
					</h4>
					<p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
				</td>
				<td>
					<div class="star-rating"></div>
					<p><%= review.rating %></p> 
					<p><%= review.comment %></p>
					<% if user_signed_in? %>
						<% if (review.user == current_user) || (current_user.admin?) %>
							<%= link_to "Edit", edit_delivery_review_path(@delivery, review), class: "btn btn-link" %> |
							<%= link_to "Delete", delivery_review_path(@delivery, review), method: :delete, class: "btn btn-link" %>
						<% end %>
					<% end %>					
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>		
	<% end %>
	</div>
</div>

<script>
	$('.star-rating').raty();
</script>

app/views/layouts/_bootstrap.html.erb
  <!-- Latest compiled and minified CSS -->
<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JQuery -->
	<script src="//code.jquery.com/jquery-3.1.1.min.js"></script>

	<!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<%= image_tag "https://s3.amazonaws.com/nextpakk/app-footer-image-web-app-1200w.jpg", class: "img-responsive" %>
<p>Copyright Lowell Fortune 2016</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "nextpakk", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", pages_contact_path %></li>       
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
         <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nextpakkgo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/bootstrap' %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container-fluid" style="margin-top: 70px;">

	<% flash.each do |name, msg| %>
       <%if msg.is_a?(String) %>
       		<div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
       		<button type="button" class="close" data-dimiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
       		<%= content_tag :div, msg, :id => "flash_#{name}" %>
       		</div>
       		<% end %>
       		<% end %>
		<%= yield %><br />
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to NextPakk Go Package Delivery Service</h1>
<h2>Smart, Secure, Convenient! "We've Got Your Pack"</h2>

app/views/pages/contact.html.erb
<h1>We would love to <%= link_to "Deliver", "http://www.deliver.com" %> your packages.</h1>
<p>Contact us at delivery@nextpackgo.com.</p>

app/views/reviews/_form.html.erb
<%= form_for([@delivery, @review]) do |f| %>
  <% if @review.errors.any? %>
   <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
    </button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rating %><br>
    <%= f.number_field :rating, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script >
  $('#star-rating').raty({ path: 'https://s3.amazonaws.com/nextpakk/stars',  
    scoreName: 'review[rating]'  
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_path(@delivery) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', delivery_path(@delivery) %>